### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by JackyCZJ** [hzwesoft-github/underscore#1]
应该是国人所以我直接说中文了
https://github.com/hzwesoft-github/underscore/blob/2725a89ff641953336516988004bbcee9c17f09c/openwrt/blobbuf_cgo.go#L18-L24
这里面的calloc没有一处地方有free的，作为ubus调用久了之后会产生内存溢出。

**Comment by zddava** [comment]
> 应该是国人所以我直接说中文了
> 
> https://github.com/hzwesoft-github/underscore/blob/2725a89ff641953336516988004bbcee9c17f09c/openwrt/blobbuf_cgo.go#L18-L24
> 
> 
> 这里面的calloc没有一处地方有free的，作为ubus调用久了之后会产生内存溢出。

感谢！这个项目是给公司一个开发中的产品做支撑用的，这个产品由于某些原因暂停开发了，所以这个库实际并没有写完，并且没有在实际环境中测试过。

这个代码我都忘掉了，刚刚回看了一下，这里应该是在它自己的Close()方法中释放吧
`func (buf *BlobBuf) Free() {
	C.blob_buf_free(buf.ptr)
}`

**Comment by JackyCZJ** [comment]
blob_buf_free 只是 free掉了blobbuf 而已，而memset所申请的内存则需要用free来清理干净。
```
type BlobBuf struct {
	ptr *C.struct_blob_buf
}

var p = C.calloc(1, C.sizeof_struct_blob_buf)
var _ = C.memset(p, 0, C.sizeof_struct_blob_buf)
var B = &BlobBuf{
	ptr: (*C.struct_blob_buf)(p),
}


func NewBlobBuf() *BlobBuf {
	return B
}

```


我改成了这样就没啥问题了，就一直使用第一次申请的内存。
